---
version: '3.2'

networks:
  mqtt_net:
    driver: bridge

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    networks:
      - mqtt_net

  scan_reader:
    build:
      context: ./scan-reader
    environment:
      MQTT_HOST_IP: 'mqtt'
    networks:
      - mqtt_net
    volumes:
      - ./testdata/:/data/:ro

  page_detector:
    build:
      context: ./page-detector
    environment:
      MQTT_HOST_IP: 'mqtt'
    networks:
      - mqtt_net
    volumes:
      - ./testdata/:/data/:rw
